[build]
  command = "npm run build"
  publish = "out"
  base = "frontend/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API calls 
[[redirects]]
  from = "/api/*"
  to = "https://property-board.onrender.com/api/:splat"
  status = 200
  force = true
